version: "3.2"
services:
 docker_api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - 5001:5001
 rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - rabbitmq_go_net

networks:
  api-network:
    external: true
    name: api-network
  rabbitmq_go_net:
    driver: bridge
    name: api-network

